version: '3'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: 
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    expose:
      - "3306"

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "443:443"
    restart: always

  wordpress:
    container_name: wordpress
    env_file: 
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: always
    expose:
      - "9000"
  ftp:
    container_name: ftp
    build: requirements/bonus/ftp
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    ports:
      - "21:21"
    networks:
      - inception
    restart: always

  admin:
    container_name: admin
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: always

  
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/aechaoub/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/aechaoub/data/mariadb'

networks:
  inception:
    driver: bridge
